# REUSE licensing information association file
#
# References:
#
# * REUSE.toml | REUSE Specification – Version 3.2 | REUSE
#   https://reuse.software/spec-3.2/#reusetoml
#
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

version = 1

[[annotations]]
path = [
    "topic-avatar*.jpg"
]
SPDX-FileCopyrightText = '1970 AI-generated image() <https://aistudio.google.com/prompts/1TFP6bGkRRq9AuocQX45Ic8TVCvaKxnGB?model=gemini-2.0-flash-preview-image-generation>'
SPDX-License-Identifier = 'CC0-1.0'
